jobs:

# sync pipeline to CI
  - name: now-site_runCI
    type: runCI
    steps:
      - OUT: now-site-img

# manifest gen
  - name: now-site-man
    type: manifest
    steps:
      - IN: now-site-img
      - IN: now-site-opts-dev
      - TASK: managed
    flags:
      - now-site

# DEV deployment for VISUALIZER to Amazon ECS
  - name: now-site-dev-deploy
    type: deploy
    always:
      - NOTIFY: slack-notifications
    steps:
      - IN: now-site-man
        force: true
      - IN: env-dev-ecs
      - IN: now-site-params-dev
      - IN: now-site-alb-dev
        applyTo:
          - manifest: now-site-man
            image: now-site-img
            port: 3001
      - TASK: managed
        deployMethod: upgrade

# Test Dev site
  - name: now-site-dev-automation-test
    type: runSh
    always:
      - NOTIFY: slack-notifications
    steps:
     - IN: env-dev-ecs
     - IN: now-site-repo
     - IN: now-site-alb-dev
     - IN: now-site-dev-deploy
     - TASK:
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "6.1.0"
        - script: nvm use "6.1.0"
        - script: cd ./IN/now-site-repo/gitRepo/automation
        - script: npm set registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: npm run test:phantom

# Package release to staging
  - name: now-site-staging-release
    type: release
    steps:
      - IN: now-site-version
#        switch: off
      - IN: now-site-dev-deploy
#        switch: off
      - TASK: managed
        bump: minor

# Deploy to staging - will currently autodeploy to staging on release creation above
  - name: now-site-staging-deploy
    type: deploy
    always:
      - NOTIFY: slack-notifications
    steps:
      - IN: now-site-staging-release
        #switch: off - if we don't want to autodeploy.
      - IN: env-staging-ecs
      - IN: now-site-staging-deploy-trigger
      - IN: now-site-params-staging
      - IN: now-site-replicas-staging
      - IN: now-site-opts-staging
      - IN: now-site-alb-staging
        applyTo:
          - manifest: now-site-man
            image: now-site-img
            port: 3001
      - TASK: managed
        deployMethod: upgrade
