triggers:
  # incrementing this will drigger a staging deployment
  - name: now-site-staging-deploy-trigger
    type: trigger
    version:
      counter: 1

  # incrementing this will drigger a production deployment
  - name: now-site-prod-deploy-trigger
    type: trigger
    version:
      counter: 1
