# This jobs are only used for MULTISITE

####################################################################
# Refer to http://docs.shippable.com/reference/jobs-overview/      #
# Resources are located in shippable.resources.yml file            #
# Jobs are numbered to visualize sequence                          #
####################################################################

jobs:

  # 1. Sync pipeline to CI
  - name: multi-site_runCI
    type: runCI
    steps:
      - OUT: cosmo-site-img-master
      - OUT: cosmo-site-img-branch
      - OUT: elle-site-img-master
      - OUT: elle-site-img-branch
      - OUT: hb-site-img-master
      - OUT: hb-site-img-branch
    flags:
      - multi-site

  # 2branchCOSMO. Manifest for a BRANCH image
  - name: cosmo-site-man-branch
    type: manifest
    steps:
      - IN: cosmo-site-img-branch
      - IN: cosmo-site-opts-sit
      - TASK: managed

  # 2COSMO. Manifest for MASTER image
  - name: cosmo-site-man-master
    type: manifest
    steps:
      - IN: cosmo-site-img-master
      - IN: cosmo-site-opts-sit
      - TASK: managed

  # 2branchELLE. Manifest for a BRANCH image
  - name: elle-site-man-branch
    type: manifest
    steps:
      - IN: elle-site-img-branch
      - IN: elle-site-opts-sit
      - TASK: managed

  # 2ELLE. Manifest for MASTER image
  - name: elle-site-man-master
    type: manifest
    steps:
      - IN: elle-site-img-master
      - IN: elle-site-opts-sit
      - TASK: managed

  # 2branchHB. Manifest for a BRANCH image
  - name: hb-site-man-branch
    type: manifest
    steps:
      - IN: hb-site-img-branch
      - IN: hb-site-opts-sit
      - TASK: managed

  # 2HB. Manifest for MASTER image
  - name: hb-site-man-master
    type: manifest
    steps:
      - IN: hb-site-img-master
      - IN: hb-site-opts-sit
      - TASK: managed

  # 3a. TEST deployment for MASTER - stubbed and hb config
  - name: multi-site-test-deploy-master
    type: deploy
    steps:
      - IN: elle-site-man-master
        switch: on
      - IN: multi-env-sit-ecs
      - IN: multi-site-params-test
      - IN: multi-site-alb-test
        applyTo:
          - manifest: elle-site-man-master
            image: elle-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: replace

  # 3BranchCOSMO. SIT deployment for feature BRANCH
  - name: cosmo-site-sit-deploy-branch
    type: deploy
    always:
      - NOTIFY: multi-slack-notifications
    steps:
      - IN: cosmo-site-man-branch
        switch: off
      - IN: multi-env-sit-ecs
      - IN: multi-site-params-sit
      - IN: cosmo-site-alb-sit-branch
        applyTo:
          - manifest: cosmo-site-man-branch
            image: cosmo-site-img-branch
            port: 3001
      - TASK: managed
        deployMethod: replace

  # 3COSMO. SIT deployment for MASTER
  - name: cosmo-site-sit-deploy-master
    type: deploy
    always:
      - NOTIFY: multi-slack-notifications
    steps:
      - IN: cosmo-site-man-master # for master - auto deploy to SIT
        switch: on
      - IN: multi-env-sit-ecs
      - IN: multi-site-params-sit
      - IN: cosmo-site-alb-sit
        applyTo:
          - manifest: cosmo-site-man-master
            image: cosmo-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: replace

  # 3BranchELLE. SIT deployment for feature BRANCH
  - name: elle-site-sit-deploy-branch
    type: deploy
    always:
      - NOTIFY: multi-slack-notifications
    steps:
      - IN: elle-site-man-branch
        switch: off
      - IN: multi-env-sit-ecs
      - IN: multi-site-params-sit
      - IN: elle-site-alb-sit-branch
        applyTo:
          - manifest: elle-site-man-branch
            image: elle-site-img-branch
            port: 3001
      - TASK: managed
        deployMethod: replace

  # 3ELLE. SIT deployment for MASTER
  - name: elle-site-sit-deploy-master
    type: deploy
    always:
      - NOTIFY: multi-slack-notifications
    steps:
      - IN: elle-site-man-master # for master - auto deploy to SIT
        switch: on
      - IN: multi-env-sit-ecs
      - IN: multi-site-params-sit
      - IN: elle-site-alb-sit
        applyTo:
          - manifest: elle-site-man-master
            image: elle-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: replace

  # 3BranchHB. SIT deployment for feature BRANCH
  - name: hb-site-sit-deploy-branch
    type: deploy
    always:
      - NOTIFY: multi-slack-notifications
    steps:
      - IN: hb-site-man-branch # for non-master, don't auto deploy.
        switch: off
      - IN: multi-env-sit-ecs
      - IN: multi-site-params-sit
      - IN: hb-site-alb-sit-branch
        applyTo:
          - manifest: hb-site-man-branch
            image: hb-site-img-branch
            port: 3001
      - TASK: managed
        deployMethod: replace

  # 3HB. SIT deployment for MASTER
  - name: hb-site-sit-deploy-master
    type: deploy
    always:
      - NOTIFY: multi-slack-notifications
    steps:
      - IN: hb-site-man-master # for master - auto deploy to SIT
        switch: on
      - IN: multi-env-sit-ecs
      - IN: multi-site-params-sit
      - IN: hb-site-alb-sit
        applyTo:
          - manifest: hb-site-man-master
            image: hb-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: replace

  # 4a. Run regression test on TEST environment
  - name: multi-site-automation-test
    type: runSh
    always:
    - NOTIFY: multi-slack-notifications
    - NOTIFY: multi-qa-team-notifications
    steps:
    - IN: multi-site-test-deploy-master
    - IN: multi-site-repo
      switch: off
    - TASK:
       - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
       - script: source ~/.nvm/nvm.sh
       - script: nvm install "6.1.0"
       - script: nvm use "6.1.0"
       - script: cd ./IN/multi-site-repo/gitRepo/automation
       - script: npm set registry http://npm.digital.bauer-media.net.au
       - script: npm install
       - script: export APP_KEY=elle-site
       - script: export URL=http://multi-site.test.bxm.net.au/
       - script: npm run test:high || true
       - script: actualsize=$(wc -c <"@rerun.txt")
       - script: bash -c "if [ $actualsize -eq 0 ]; then  echo 'rerun exit code' $actualsize; else npm run test:rerun; fi"

  # 4b. Run mobile regression test on TEST environment - Browser Stack
  - name: mobile-multi-site-automation-test
    type: runSh
    always:
    - NOTIFY: multi-slack-notifications
    steps:
    - IN: multi-site-test-deploy-master
    - IN: multi-site-repo
      switch: off
    - TASK:
       - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
       - script: source ~/.nvm/nvm.sh
       - script: nvm install "6.1.0"
       - script: nvm use "6.1.0"
       - script: cd ./IN/multi-site-repo/gitRepo/automation
       - script: npm set registry http://npm.digital.bauer-media.net.au
       - script: npm install
       - script: export APP_KEY=elle-site
       - script: rm -rf node_modules/chimp/dist/lib/cucumberjs/hooks.js
       - script: cp features/support/files/chimp_hooks.backup node_modules/chimp/dist/lib/cucumberjs/hooks.js
       - script: export URL=http://multi-site.test.bxm.net.au/
       - script: npm run test:mobile

  # 4cCOSMO. Run smoke test on TEST environment COSMO
  - name: cosmo-site-smoke-test
    type: runSh
    always:
    - NOTIFY: multi-slack-notifications
    - NOTIFY: multi-qa-team-notifications
    steps:
    - IN: cosmo-site-sit-deploy-master
    - IN: multi-site-repo
      switch: off
    - TASK:
       - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
       - script: source ~/.nvm/nvm.sh
       - script: nvm install "6.1.0"
       - script: nvm use "6.1.0"
       - script: cd ./IN/multi-site-repo/gitRepo/automation
       - script: npm set registry http://npm.digital.bauer-media.net.au
       - script: npm install
       - script: export APP_KEY=cosmo-site
       - script: export URL=http://cosmo-site-au.sit.bxm.net.au/
       - script: npm run smoketest:cosmo

  # 4cELLE. Run smoke test on TEST environment ELLE
  - name: elle-site-smoke-test
    type: runSh
    always:
    - NOTIFY: multi-slack-notifications
    - NOTIFY: multi-qa-team-notifications
    steps:
    - IN: elle-site-sit-deploy-master
    - IN: multi-site-repo
      switch: off
    - TASK:
       - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
       - script: source ~/.nvm/nvm.sh
       - script: nvm install "6.1.0"
       - script: nvm use "6.1.0"
       - script: cd ./IN/multi-site-repo/gitRepo/automation
       - script: npm set registry http://npm.digital.bauer-media.net.au
       - script: npm install
       - script: export APP_KEY=elle-site
       - script: export URL=http://elle-site-au.sit.bxm.net.au/
       - script: npm run smoketest:elle

  # 4cHB. Run smoke test on TEST environment HB
  - name: hb-site-smoke-test
    type: runSh
    always:
    - NOTIFY: multi-slack-notifications
    - NOTIFY: multi-qa-team-notifications
    steps:
    - IN: hb-site-sit-deploy-master
    - IN: multi-site-repo
      switch: off
    - TASK:
       - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
       - script: source ~/.nvm/nvm.sh
       - script: nvm install "6.1.0"
       - script: nvm use "6.1.0"
       - script: cd ./IN/multi-site-repo/gitRepo/automation
       - script: npm set registry http://npm.digital.bauer-media.net.au
       - script: npm install
       - script: export APP_KEY=hb-site
       - script: export URL=http://hb-site-au.sit.bxm.net.au/
       - script: npm run smoketest:hb

  # 5COSMO. Package release for production release
  - name: cosmo-release-master
    type: release
    steps:
      - IN: multi-site-automation-test
      - IN: cosmo-site-version
      - IN: cosmo-site-man-master
        switch: off
      - TASK: managed

  # 5ELLE. Package release for production release
  - name: elle-release-master
    type: release
    steps:
      - IN: multi-site-automation-test
      - IN: elle-site-version
      - IN: elle-site-man-master
        switch: off
      - TASK: managed

  # 5HB. Package release for production release
  - name: hb-release-master
    type: release
    steps:
      - IN: multi-site-automation-test
      - IN: hb-site-version
      - IN: hb-site-man-master
        switch: off
      - TASK: managed

  # 6COSMO. PROD deployment for MASTER COSMO
  - name: cosmo-site-prod-deploy-master
    type: deploy
    always:
      - NOTIFY: multi-slack-notifications
      - NOTIFY: cosmo-deployment-notifications
    steps:
      - IN: cosmo-release-master
        switch: off
      - IN: multi-env-prod-ecs
      - IN: multi-site-params-prod
      - IN: cosmo-site-alb-prod
        applyTo:
          - manifest: cosmo-site-man-master
            image: cosmo-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: upgrade

  # 6ELLE. PROD deployment for MASTER ELLE
  - name: elle-site-prod-deploy-master
    type: deploy
    always:
      - NOTIFY: multi-slack-notifications
      - NOTIFY: elle-deployment-notifications
    steps:
      - IN: elle-release-master
        switch: off
      - IN: multi-env-prod-ecs
      - IN: multi-site-params-prod
      - IN: elle-site-alb-prod
        applyTo:
          - manifest: elle-site-man-master
            image: elle-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: upgrade

  # 6HB. PROD deployment for MASTER HB
  - name: hb-site-prod-deploy-master
    type: deploy
    always:
      - NOTIFY: multi-slack-notifications
      - NOTIFY: hb-deployment-notifications
    steps:
      - IN: hb-release-master
        switch: off
      - IN: multi-env-prod-ecs
      - IN: multi-site-params-prod
      - IN: hb-site-alb-prod
        applyTo:
          - manifest: hb-site-man-master
            image: hb-site-img-master
            port: 3001
      - TASK: managed
        deployMethod: upgrade

  ##############################################
  # Schedule jobs - not attached to the pipeline
  ##############################################
  
  
  # i. Full regression in SIT Multi
  - name: FULL-multi-site-regression-test
    type: runSh
    always:
      - NOTIFY: multi-qa-team-notifications
    steps:
     - IN: multi-site-repo
       switch: off
     - IN: multi-morning-trigger
     - TASK:
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "6.1.0"
        - script: nvm use "6.1.0"
        - script: cd ./IN/multi-site-repo/gitRepo/automation
        - script: npm set registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: export URL=http://multi-site.test.bxm.net.au/
        - script: export APP_KEY=elle-site
        - script: npm run all:test || true
        - script: actualsize=$(wc -c <"@rerun.txt")
        - script: bash -c "if [ $actualsize -eq 0 ]; then  echo 'rerun exit code' $actualsize; else npm run test:rerun; fi"
    flags:
      - multi-site

  # ii. Smoke Test in ELLE Dev CMS
  - name: CMS-elle-smoke-test
    type: runSh
    always:
      - NOTIFY: multi-qa-team-notifications
    steps:
     - IN: multi-site-repo
       switch: off
     - IN: elle-weekly-trigger
     - TASK:
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "6.1.0"
        - script: nvm use "6.1.0"
        - script: cd ./IN/multi-site-repo/gitRepo/automation
        - script: npm set registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: export URL=http://cms.dev.elle.wn.bauer-media.net.au/cms/umbraco/
        - script: export APP_KEY=elle-site
        - script: npm run test:cms || true
        - script: actualsize=$(wc -c <"@rerun.txt")
        - script: bash -c "if [ $actualsize -eq 0 ]; then  echo 'rerun exit code' $actualsize; else npm run test:rerun; fi"
    flags:
      - multi-site

  # iii. Smoke Test in HB Dev CMS
  - name: CMS-hb-smoke-test
    type: runSh
    always:
      - NOTIFY: multi-qa-team-notifications
    steps:
     - IN: multi-site-repo
       switch: off
     - IN: hb-weekly-trigger
     - TASK:
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "6.1.0"
        - script: nvm use "6.1.0"
        - script: cd ./IN/multi-site-repo/gitRepo/automation
        - script: npm set registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: export URL=http://cms.dev.hb.wn.bauer-media.net.au/cms/umbraco/
        - script: export APP_KEY=hb-site
        - script: npm run test:cms || true
        - script: actualsize=$(wc -c <"@rerun.txt")
        - script: bash -c "if [ $actualsize -eq 0 ]; then  echo 'rerun exit code' $actualsize; else npm run test:rerun; fi"
    flags:
      - multi-site

  # iv. Smoke Test in Cosmo Dev CMS
  - name: CMS-cosmo-smoke-test
    type: runSh
    always:
      - NOTIFY: multi-qa-team-notifications
    steps:
     - IN: multi-site-repo
       switch: off
     - IN: cosmo-weekly-trigger
     - TASK:
        - script: curl https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
        - script: source ~/.nvm/nvm.sh
        - script: nvm install "6.1.0"
        - script: nvm use "6.1.0"
        - script: cd ./IN/multi-site-repo/gitRepo/automation
        - script: npm set registry http://npm.digital.bauer-media.net.au
        - script: npm install
        - script: export URL=http://cms.dev.cosmo.wn.bauer-media.net.au/cms/umbraco/
        - script: export APP_KEY=cosmo-site
        - script: npm run test:cms || true
        - script: actualsize=$(wc -c <"@rerun.txt")
        - script: bash -c "if [ $actualsize -eq 0 ]; then  echo 'rerun exit code' $actualsize; else npm run test:rerun; fi"
    flags:
      - multi-site