# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference # NodeJS App + Docker + ECR + ECS

# Version 2.1 with ORBS for AWS ECR | ECS and DOCKER - now-Site

version: 2.1

# ORBS

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.1.0

# JOBS

jobs:
  ecr-buildandpush-dockerimage:
    parameters:
      APP_NAME:
        type: string
        default: "Use_App_Name"
    environment:
      # Settings for APP
      APP_KEY: << parameters.APP_NAME >>
      # Settings for commons
      CLUSTER_NAME: cci-app-ecs
      APP_STUBBED: true
    machine:
      image: ubuntu-1604:202010-01
    working_directory: ~/multi-site
    steps:

# Set ENV Vars to use with ECR/DOCKER - Verify CircleCI Task
      - run:
          name: Set Env Vars - SHELL_VARIABLES
          command: |
                if [ $CIRCLE_BRANCH == master ]; then
                  CCI_BRANCH_NAME=$CIRCLE_BRANCH.$CIRCLE_BUILD_NUM;
                  echo "export BRANCH_NAME=$CCI_BRANCH_NAME" >> $BASH_ENV;
                  echo "export SERVICE_NAME=sit-master-$APP_KEY-service-v1" >> $BASH_ENV;
                  echo "export TASK_NAME=sit-master-$APP_KEY-task" >> $BASH_ENV;
                  echo "export TASKDEF_JSON_FILENAME=sit-master-$APP_KEY-task-def-json" >> $BASH_ENV;
                  echo "export REPOS_NAME=cci-$APP_KEY" >> $BASH_ENV;
                  echo "export CONTAINER_NAME=$APP_KEY-container" >> $BASH_ENV;
                  echo "export IMAGE_NAME=$CCI_BRANCH_NAME" >> $BASH_ENV;
                fi
                if [ $CIRCLE_BRANCH != master ]; then
                  CCI_BRANCH_NAME=$(echo $CIRCLE_BRANCH | sed -e 's/\//-/g').$CIRCLE_BUILD_NUM;
                  echo "export BRANCH_NAME=$CCI_BRANCH_NAME" >> $BASH_ENV;
                  echo "export SERVICE_NAME=sit-branch-$APP_KEY-service-v1" >> $BASH_ENV;
                  echo "export TASK_NAME=sit-branch-$APP_KEY-task" >> $BASH_ENV;
                  echo "export TASKDEF_JSON_FILENAME=sit-branch-$APP_KEY-task-def-json" >> $BASH_ENV;
                  echo "export REPOS_NAME=cci-$APP_KEY" >> $BASH_ENV;
                  echo "export CONTAINER_NAME=$APP_KEY-container" >> $BASH_ENV;
                  echo "export IMAGE_NAME=$CCI_BRANCH_NAME" >> $BASH_ENV;
                fi

# Print ENV Vars - Verify CircleCI ENV
      - run:
          name: Print Env Vars - Verify
          command: |
                echo "APP_NAME=$APP_KEY";
                echo "BRANCH_NAME=$BRANCH_NAME";
                echo "CLUSTER_NAME=$CLUSTER_NAME";
                echo "SERVICE_NAME=$SERVICE_NAME";
                echo "TASK_NAME=$TASK_NAME";
                echo "TASKDEF_JSON_FILENAME=$TASKDEF_JSON_FILENAME";
                echo "REPOS_NAME=$REPOS_NAME";
                echo "CONTAINER_NAME=$CONTAINER_NAME"
                echo "IMAGE_NAME=$IMAGE_NAME";

# Code Checkout - CCI_Build
      - checkout

# Prepare the VM for NodeJS App Build
      - run:
          name: "Install | NVM | NPM | NODE_JS"
          command: |
                echo -e "\n\n\n ### UBUNTU_16.04 | NVM | NPM | NODE_JS "
                echo -e "\n ### Install NVM (Node Version Manager) - Installer for NodeJS + NPM "
                curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
                source ~/.profile
                nvm install v10.19.0
                echo -e "\n ### Setting Default NVM "
                nvm use v10.19.0;
                echo -e "\n ### Setting NPM Registry as BXM "
                npm set @bxm:registry http://npm.digital.bauer-media.net.au
                cd src; pwd;
                npm install
                npm rebuild node-sass --force
                npm run test:ci
                NODE_ENV=production npm run build
                echo -e "\n ### Version Information "
                echo -e "\n ### NVM Version  : $(nvm --version)"
                echo -e "\n ### NPM Version  : $(npm --version)"
                echo -e "\n ### Node Version : $(node --version)"
                echo -e "\n ### Docker Version : $(docker --version)"

# AWS ECR Integration: Build and Push Docker Image to ECR
      - aws-ecr/build-and-push-image:
          checkout: false  # Checkout already done in previous step
          profile-name: profile
          aws-access-key-id: ECR_AWS_ACCESS_KEY_ID
          aws-secret-access-key: ECR_AWS_SECRET_ACCESS_KEY
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_DEFAULT_REGION
          repo: $REPOS_NAME
          create-repo: true
          repo-scan-on-push: false
          dockerfile: Dockerfile
          no-output-timeout: 9m # 9 minutes
          tag: '$IMAGE_NAME,latest'

# AWS ECS Integration: Create a task definition using JSON: path-to/json-file.json
      - aws-ecs/update-task-definition-from-json:
          task-definition-json: $TASKDEF_JSON_FILENAME

# AWS ECS Integration: [ Cluster | Service | Task | PullImage-ECR | Deploy-NodeJS-APP ]
      - aws-ecs/update-service:
          cluster-name: arn:aws:ecs:ap-southeast-2:014901580825:cluster/$CLUSTER_NAME
          service-name: $SERVICE_NAME
          family: $TASK_NAME
          container-image-name-updates: "container=$CONTAINER_NAME,tag=$IMAGE_NAME"
          skip-task-definition-registration: false # Don't Skip
          force-new-deployment: true
          verify-revision-is-deployed: true
          verification-timeout: 9m
          max-poll-attempts: 10
          poll-interval: 120 # check deployment status every 2 minutes

# WORKFLOWS

workflows:
  version: 2
  multi-site-build:
    jobs:

# gt - SITE
      - ecr-buildandpush-dockerimage:
          APP_NAME: gt-site
          filters:
            branches:
              only:
                - circleci-project-setup
                - master
                - /fix.*/
                - /feature.*/
                - /dependabot.*/
              ignore:
                - main

# elle - SITE
      - ecr-buildandpush-dockerimage:
          APP_NAME: elle-site
          filters:
            branches:
              only:
                - circleci-project-setup
                - master
                - /fix.*/
                - /feature.*/
                - /dependabot.*/
              ignore:
                - main

# awwfood - SITE
      - ecr-buildandpush-dockerimage:
          APP_NAME: awwfood-site
          filters:
            branches:
              only:
                - circleci-project-setup
                - master
                - /fix.*/
                - /feature.*/
                - /dependabot.*/
              ignore:
                - main

# foodnz - SITE
      - ecr-buildandpush-dockerimage:
          APP_NAME: foodnz-site
          filters:
            branches:
              only:
                - circleci-project-setup
                - master
                - /fix.*/
                - /feature.*/
                - /dependabot.*/
              ignore:
                - main


# hb - SITE
      - ecr-buildandpush-dockerimage:
          APP_NAME: hb-site
          filters:
            branches:
              only:
                - circleci-project-setup
                - master
                - /fix.*/
                - /feature.*/
                - /dependabot.*/
              ignore:
                - main



### END ###

#       echo -e "\n ### This is pipeline ID << pipeline.id >> # << pipeline.git.branch >>"
#       echo -e "\n ### This is pipeline ID << pipeline.id >> # << pipeline.git.branch >>"
#       source ~/.profile
#       tag: 'latest,$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM'
#       echo -e "\n\n\n ### CCI_BRANCHNAME: $CCI_BRANCH_NAME"
#       APP_KEY_GT: gt-site
#       APP_KEY_ELLE: elle-site
#       APP_KEY_FOODNZ: foodnz-site
#       APP_KEY_AWWFOOD: awwfood-site
#       APP_KEY_HB: hb-site
#       APP_KEY=cosmo-site
