var cms_widget = {

    loginUsername: 'input#lname',
    loginPassword: 'input#passw',
    loginButton: 'input[value="Login"]',
    cmsLeftSide: '#leftDIV',
    cmsRightSide: '#rightDIV',
    createName: 'input.bigInput',
    createDocumentType: 'select.bigInput',
    createButton: 'input[value="Create"]',
    itemTabs: '#body_TabView1',
    editorialLongTitle: 'div[module-id="contentTitle"] input',
    editorialShortTeaser: 'div[module-id="contentSummary"] textarea',
    editorialImage: 'input[id="body_txtbody_prop_contentImageUrl_fuCougarUploader"]',
    editorialBodyComponentList:'select[ng-model="newComponent"]',
    editorialBodyParagraphOption: 'option[value="0"]',
    editorialBodyHeadingOption: 'option[value="1"]',
    editorialBodyAddButton: 'button[ng-click="addComponent()"]',
    editorialBodyParagraph: '.content-body-component textarea.markdown-input',
    editorialBodyHeading: '.content-body-editor .form-control.one-half.ng-pristine.ng-valid',
    ampDisableBox: '[ng-init="init(\'disableAmp\')"] div.col-xs-10 > input',
    ampHtml: 'link[rel=amphtml]',
    searchAndSocialPageTitle: 'div[module-id="pageTitle"] input',
    searchBox: '#umbSearchField',
    searchResult: '.ac_results',
    menuDelete: '.menuSpr.sprDelete',
    unpublishButton: '[value="Unpublish"]',
    propertiesCreatedAt: '.tabpageContent div:nth-child(9) .umbDateTimePicker input',
    editorialUseVideo: 'video-uploader div > div:nth-child(n) > div >div.bordered-group > input',
    editorialVideoAddButton: 'video-uploader > div div:nth-child(n) > div > div.bordered-group div button',
    editorialVideoId: '.tw-bs.module.video .panel [ng-show="data.videoId"] td.ng-binding',
    editorialAddVideoButton: 'search-videos > div > div.top-five-latest-videos.bordered-group > div:nth-child(1) > div.video-info > div.button-group > button',
    editorialVideoThumbnail: 'div.propertyItem > div > div > div > div.preview.ng-scope > div:nth-child(2) > img',
    editorialSecondVideoThumbnail: 'video-uploader > div > div > div.preview.ng-scope > div:nth-child(2) > img',
    editorialSearchVideo: 'div > div:nth-child(2) > input.form-control.one-half.ng-pristine.ng-valid',
    editorialSearchButton: 'div > div:nth-child(2) > input.btn.btn-primary',
    editorialBodyVideoOption: 'option[value="5"]',
    editorialMagazineIssue: 'input#body_prop_contentMagazineIssue',
    editorialStyling: 'input#body_prop_contentStyling',
    editorialAddress: '[ng-init="init(\'contentAddress\')"] textarea',
    editorialHours: '[ng-init="init(\'contentHours\')"] textarea',
    editorialPrices: '[ng-init="init(\'contentPrices\')"] textarea',
    pageContentTags: 'tag-picker [ng-model="item.tagName"]',
    pageContentTagsFirstTag: 'a.ng-scope.ng-binding > strong',
    pageContentTagsDropDown: 'ul#typeahead-01Y-9026.dropdown-menu.ng-scope',
    recipeRecipeServings: '.recipe-serves-yield-item',
    recipeRecipeServingsMin: '.recipe-serves-yield-item [id="serveMin"]',
    recipeRecipeServingsMax: '.recipe-serves-yield-item [id="serveMax"]',
    recipeRecipeServingsQuantity: '.recipe-serves-yield-item [id="yieldQuantity"]',
    recipeRecipeServingsMeasure: '.recipe-serves-yield-item [id="yieldMeasure"]',
    recipeCookingTime: '.recipe-cooking-time',
    recipeCookingTimePreparationTime: '.recipe-cooking-time__list:nth-child(1) [ng-model="item.quantity"]',
    recipeCookingTimePreparationTimeLabel: '.recipe-cooking-time__list:nth-child(1) [content="item.label"] textarea',
    recipeCookingTimeCookingTime: '.recipe-cooking-time__list:nth-child(2) [ng-model="item.quantity"]',
    recipeCookingTimeCookingTimeLabel: '.recipe-cooking-time__list:nth-child(2) [content="item.label"] textarea',
    recipeCookingTimeMarinatingTime: '.recipe-cooking-time__list:nth-child(3) [ng-model="item.quantity"]',
    recipeCookingTimeMarinatingTimeLabel: '.recipe-cooking-time__list:nth-child(3) [content="item.label"] textarea',
    recipeIngredients: '.recipe-ingredients',
    recipeIngredientsQuantity1: '.recipe-ingredients-list__item:nth-child(1) [ng-model="item.quantity"]',
    recipeIngredientsMeasure1: '.recipe-ingredients-list__item:nth-child(1) [ng-model="item.measure"]',
    recipeIngredientsIngredient1: '.recipe-ingredients-list__item:nth-child(1) [content="item.ingredient"] textarea',
    recipeIngredientsQuantity2: '.recipe-ingredients-list__item:nth-child(2) [ng-model="item.quantity"]',
    recipeIngredientsMeasure2: '.recipe-ingredients-list__item:nth-child(2) [ng-model="item.measure"]',
    recipeIngredientsIngredient2: '.recipe-ingredients-list__item:nth-child(2) [content="item.ingredient"] textarea',
    recipeCookingMethod: '.recipe-cooking-method',
    recipeCookingMethodHeading: '.recipe-cooking-method-group [ng-model="group.heading"]',
    recipeCookingMethodText: '.recipe-cooking-method-list__item:nth-child(1) textarea',
    recipeRecipeTips: '.markdown-textbox',
    recipeRecipeTipsText: '.markdown-textbox textarea',


};

module.exports = cms_widget;
