var homepage_widget = {

    mustreadHeader: '.mustread-teaser-view-grid .home-page__teasers-title',
    mustreadImage: '.mustread-teaser-view-grid .teaser__list-item .teaser__inner img',
    mustreadImageLink: '.mustread-teaser-view-grid .teaser__list-item .teaser__inner > a',
    mustreadTitle: '.mustread-teaser-view-grid .teaser__list-item .teaser__title a',
    promotedHeader: '.promoted-teaser-view-grid .home-page__teasers-title',
    promotedImage: '.promoted-teaser-view-grid .teaser__list-item .teaser__inner img',
    promotedImageLink: '.promoted-teaser-view-grid .teaser__list-item .teaser__inner > a',
    promotedSectionTag: '.promoted-teaser-view-grid a.teaser__section-tag',
    promotedTitle: '.promoted-teaser-view-grid .teaser__list-item .teaser__title a',
    heroImg: '.hero-wrapper .hero-teaser',
    heroImgUrl: '.hero-wrapper .hero-teaser img',
    heroImgLink: '.hero-wrapper .hero-teaser .teaser__image',
    heroCustomLabel: '.hero-wrapper .teaser__badge',
    heroLabelPosition: '.hero-wrapper .teaser__sub-section-container',
    heroTitle: '.hero-wrapper .teaser__title a',
    heroShortTeaser: '.hero-wrapper .teaser__summary',
    heroSource: '.hero-wrapper .hero-teaser__source',
    heroStyle: '.content-wrapper .stripe-bg',
    trendingTitle: '.trending__caption.hide-for-xlarge-up img',
    bottomFeed: '.teaser__list.teaser-view-list',
    topFeedGridNumber: '.teaser__list.teaser-view-grid article.teaser',
    topFeedGridTeaserImg: '.teaser__list.teaser-view-grid .teaser__image img',
    topFeedGridTeaserImgLink: '.teaser__list.teaser-view-grid .teaser__image',
    topFeedGridTeaserTitle: '.teaser__list.teaser-view-grid .teaser__title a',
    topFeedGridTeaserSource: '.teaser__list.teaser-view-grid .teaser__source',
    topFeedListNumber: '.top-news-feed .teaser__list.teaser-view-list article.teaser',
    topFeedListTeaserImg: '.top-news-feed .teaser__list.teaser-view-list .teaser__image img',
    topFeedListTeaserImgLink: '.top-news-feed .teaser__list.teaser-view-list .teaser__image',
    topFeedListTeaserTitle: '.top-news-feed .teaser__list.teaser-view-list .teaser__title a',
    topFeedListTeaserSource: '.top-news-feed .teaser__list.teaser-view-list .teaser__source',
    bottomFeedListNumber: '.bottom-news-feed .teaser__list.teaser-view-list article.teaser',
    bottomFeedListTeaserImg: '.bottom-news-feed .teaser__list.teaser-view-list .teaser__image img',
    bottomFeedListTeaserImgLink: '.bottom-news-feed .teaser__list.teaser-view-list .teaser__image',
    bottomFeedListTeaserTitle: '.bottom-news-feed .teaser__list.teaser-view-list .teaser__title a',
    bottomFeedListTeaserSource: '.bottom-news-feed .teaser__list.teaser-view-list .teaser__source',
    rhsSocialLink: '.page__social-wrapper .social-link a',
    newsletterSignUpBtnDesktop: '.page__social-wrapper .newsletter-subscribe__button a',
    newsletterSignUpBtnMobile: '.hero-wrapper .newsletter-subscribe__button a',
    loadMoreFeed: '.repeatable-component div:nth-child(2) article',
    loadMoreFeedTeaserImg: '.repeatable-component div:nth-child(2) li.teaser__list-item:nth-child(1) article .teaser__image img',
    loadMoreFeedTeaserImgLink: '.repeatable-component div:nth-child(2) li.teaser__list-item:nth-child(1) article .teaser__image',
    topSearchBox: '.page-search-box',
    topSearchBoxSearchBar: '.page-search-box .search-bar'
};

module.exports = homepage_widget;
