module.exports = {
    elle: {
        'homepage': 'https://www.sit.elle.com.au/',
        'section': 'fashion',
        'tag': 'tags/street-style',
        'article': 'celebrity/kourtney-kardashian-39th-birthday-pinatas-12635',
        'gallery': 'culture/elle-australia-stella-mccartney-beach-cleanup-12919',
        'amp article': 'amp/celebrity/kourtney-kardashian-39th-birthday-pinatas-12635',
        'amp gallery': 'amp/culture/elle-australia-stella-mccartney-beach-cleanup-12919',
        'keyword1': 'birthday',
        'keyword2': 'her'
    },
    gt: {
        'homepage': 'https://www.sit.gourmettraveller.com.au/',
        'section': 'travel',
        'subsection': 'travel/destinations',
        'tag': 'tags/travel',
        'article': 'news/food-news/best-bacon-in-australia-32030',
        'gallery': 'news/food-news/ramen-tshirts-uniqlo-32108',
        'review': 'dining-out/restaurant-reviews/queen-chow-enmore-32150',
        'recipe collection': 'recipes/recipe-collections/fillo-pastry-recipes-32061',
        'recipe': 'recipes/chefs-recipes/smashed-cucumber-salad-31442',
        'amp article': 'amp/news/food-news/best-bacon-in-australia-32030',
        'amp gallery': 'amp/news/food-news/ramen-tshirts-uniqlo-32108',
        'amp review': 'amp/dining-out/restaurant-reviews/queen-chow-enmore-32150',
        'amp recipe collection': 'amp/recipes/recipe-collections/fillo-pastry-recipes-32061',
        'amp recipe': 'amp/recipes/chefs-recipes/smashed-cucumber-salad-31442',
        'keyword1': 'beef',
        'keyword2': 'chicken'
    },
    awwfood: {
        'homepage': 'https://www.sit.womensweeklyfood.com.au/',
        'section': 'recipes',
        'tag': 'tags/cake',
        'article': 'salmon-recipes-for-breakfast-2411',
        'gallery': 'guinness-world-records-food-31104',
        'recipe collection': 'chip-recipes-31841',
        'recipe' : 'recipes/sweet-potato-rosti-with-salmon-3935',
        'amp article': 'amp/salmon-recipes-for-breakfast-2411',
        'amp gallery': 'amp/guinness-world-records-food-31104',
        'amp recipe collection': 'amp/chip-recipes-31841',
        'amp recipe' : 'amp/recipes/sweet-potato-rosti-with-salmon-3935',
        'keyword1': 'beef',
        'keyword2': 'chicken'
    },
    foodnz: {
        'homepage': 'https://www.sit.foodtolove.co.nz/',
        'section': 'recipes',
        'tag': 'tags/cake',
        'article': 'create-impressive-summer-entertaining-platter-1336',
        'gallery': '10-of-food-magazines-all-time-favourite-desserts-32373',
        'recipe collection': '12-sweet-coconut-treats-made-for-special-occasions-32949',
        'recipe' : 'recipes/burnt-marshmallow-coconut-cones-31900',
        'amp article': 'amp/create-impressive-summer-entertaining-platter-1336',
        'amp gallery': 'amp/10-of-food-magazines-all-time-favourite-desserts-32373',
        'amp recipe collection': 'amp/12-sweet-coconut-treats-made-for-special-occasions-32949',
        'amp recipe' : 'amp/recipes/burnt-marshmallow-coconut-cones-31900',
        'keyword1': 'beef',
        'keyword2': 'chicken'
    }
};
